spring:
  application:
    name: template
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
  jpa:
    show-sql: true

logging:
  level:
    br.com.akj: DEBUG

### LIQUIBASE ###
liquibase:
  enabled: true
  liquibase-schema: hello-user