name: Tests

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ main ]

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml'

      - name: Run tests with Maven
        run: mvn -B test
      - name: Run integration tests with Maven
        run: mvn -B integration-test